services:

  db:
    restart: unless-stopped
    container_name: rdan_db
    image: library/postgres:17.2
    env_file:
      - ./postgres/.env
    volumes:
      - type: volume
        source: rdan-db
        target: /var/lib/postgresql/data
    ports:
      # Docker, by default, binds to 0.0.0.0 :/
      - 127.0.0.1:32800:5432

  bot:
    restart: unless-stopped
    container_name: rdan_bot
    build: .
    depends_on:
      - db
    volumes:
      # allows us to access files downloaded from sonarr
      - ./servarr/data:/data
      - type: bind
        source: ./cogs
        target: /main/cogs
        read_only: true

      - type: bind
        source: ./utils
        target: /main/utils
        read_only: true

      - type: bind
        source: ./postgres
        target: /main/postgres
        read_only: true

volumes:
  rdan-db:
