services:

  db:
    restart: unless-stopped
    container_name: rdan_db
    # Can be shortened with ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    build: ./postgres
    env_file:
      - ./postgres/.env
    volumes:
      - type: volume
        source: rdan-db
        target: /var/lib/postgresql/data

  sonarr:
    restart: unless-stopped
    container_name: rdan_sonarr
    image: lscr.io/linuxserver/sonarr:latest
    volumes:
      - /home/dan/robo-dan/servarr/config/sonarr:/config
      - /home/dan/robo-dan/servarr/data:/data
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 28600:8989

  sabnzbd:
    restart: unless-stopped
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: rdan_sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/dan/robo-dan/servarr/config/sabnzbd:/config
      - /home/dan/robo-dan/servarr/data/usenet:/data/usenet
    ports:
      - 28700:8080
    expose:
      - 8080

  bot:
    restart: unless-stopped
    container_name: rdan_bot
    build: .
    volumes:
      # allows us to access files downloaded from sonarr
      - /home/dan/robo-dan/servarr/data:/data
    depends_on:
      - db

volumes:
  rdan-db:
