[tool.poetry]
name = "robo dan"
version = "0.1.0"
description = ""
authors = ["Void-ux <daniel.grant2017@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = {extras = ["speed"], version = "^2.0.1"}
Pillow = "^9.2.0"
toml = "^0.10.2"
aiohttp = {extras = ["speed"], version = "^3.8.1"}
asyncpg = "^0.26.0"
colorama = "^0.4.5"
psutil = "^5.9.2"
python-dateutil = "^2.8.2"
parsedatetime = "^2.6"
jishaku = "^2.5.1"
yt-dlp = "^2022.9.1"
mystbin-py = "^5.0.2"
orjson = "^3.8.0"
uvloop = { version = "^0.16.0", markers = "sys_platform == 'linux'" }
humanize = "^4.3.0"
wavelink = "^1.3.2"
aiob2 = {git = "https://github.com/Void-ux/aiob2.git", rev = "master"}

[tool.poetry.dev-dependencies]

[tool.pyright]
venvPath = "C:\\Users\\MS1\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\"
venv = "robo_dan-2tPVQ_ju-py3.10"
typeCheckingVersion = "off"
pythonVersion = "3.10"
reportUnusedImport = "error"
reportUnnecessaryTypeIgnoreComment = "error"
reportIncompatibleMethodOverride = "error"
